server:
   port: 9000

# ~ spring
# =========================================================== 
spring: 
   application:
      name: niblet
   profiles:
      active: dev
   jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
   servlet: 
      multipart:
         max-file-size: 10MB
         max-request-size: 100MB

# ~ mybatis
# =========================================================== 
mybatis-plus:
   mapper-locations:
     - classpath:mapper/*.xml
   type-aliases-package: org.weicong.entity
   global-config:
      db-config:
        logic-delete-value: 1
        logic-not-delete-value: 0
        
mybatis:
   configuration:
      mapUnderscoreToCamelCase: true
      map-underscore-to-camel-case: true

# ~ log
# ===========================================================      
logging:
   file: ./logs/slf4j-log.log
   level: 
      org.weicong.auth: debug