spring:
   profiles: prod
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/corn?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      hikari:
         minimum-idle: 5
         maximum-pool-size: 30
         auto-commit: true
         idle-timeout: 18000
         pool-name: DatebookHikariCP
         max-lifetime: 1800000
         connection-timeout: 30000
         connection-test-query: SELECT 1
   redis: 
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 
      timeout: 200 
      lettuce:
         pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
            max-wait: -1           
            
cdbooks: 
   sysadmin: admin               # 系统超管
   exclude-path: 
      # static
      - GET/js/**
      - GET/css/**
      - GET/img/**
      - GET/images/**
      - GET/fonts/**
      # sys
      - GET/favicon.ico
      - GET/error/**
      - GET/csrf/**
      - GET/
      - GET/logout
      # swagger
      - GET/swagger-ui.html/**
      - GET/webjars/**
      - GET/swagger-resources/**
      - GET/v2/**
      # other
      - GET/null/**
      - GET/alive/**
      - GET/alive1/**
      - GET/token/**
      - GET/page/**
      - GET/download/**
      - GET/rest/*
      - GET/ex
      #- GET/rest/haha/*
      # biz
      
